# Generated by Django 6.1 on 2026-08-26 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_anonymized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(15)]),
        ),
    ]
