# Generated by Django 6.1 on 2026-09-07 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
