# Generated by Django 6.1 on 2026-09-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contributor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=8192, verbose_name='Description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=11, verbose_name='Priority')),
                ('issue_type', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('TASK', 'Task')], max_length=11, verbose_name='Issue Type')),
                ('status', models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished')], default='TO_DO', max_length=11, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_issues', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
