# Generated by Django 6.1 on 2026-09-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['-created_time', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_time', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_time', '-pk']},
        ),
    ]
